language: node_js
node_js:
- 11
env:
- DATABASE_URL=postgres://postgres@localhost/todos
before_script:
- psql -c 'create database todos;' -U postgres
- npm run db:migrate
script:
- npm test
services:
- postgresql

